# 사이트 기본 정보
title: "청주 사설구급차 서비스 | 응급환자이송단"
description: "청주를 기점으로 충북 전역에서 사설구급차 서비스를 제공합니다. 24시간 응급환자이송 서비스, 응급환자이송단 강경성 010-8841-4114"
url: "https://lds77.github.io"
baseurl: ""

# SEO 관련 설정
author: "응급환자이송단 강경성"
lang: ko-KR
locale: ko_KR

# 비즈니스 정보
business:
  name: "응급환자이송단"
  owner: "강경성"
  phone: "010-8841-4114"
  service_area: "충청북도 전역"
  location: "청주시"
  hours: "24시간 운영"

# 소셜 미디어 및 연락처
social:
  phone: "010-8841-4114"
  emergency_phone: "010-8841-4114"

# SEO 키워드
keywords: 
  - 청주 사설구급차
  - 충북 사설구급차
  - 응급환자이송
  - 청주 행사구급차
  - 충북 행사구급차
  - 사설구급차 서비스
  - 청주 응급이송
  - 충북 응급이송
  - 민간구급차
  - 환자이송
  - 응급환자이송단
  - 강경성

# 지역 정보
location:
  city: "청주시"
  region: "충청북도"
  country: "대한민국"
  latitude: 36.6424
  longitude: 127.4890

# Jekyll 설정
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Asia/Seoul

# 플러그인 (GitHub Pages에서 지원하는 플러그인들)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# 제외할 파일들
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# 검색 엔진 최적화
google_analytics: # 구글 애널리틱스 ID가 있으면 여기에 입력
google_site_verification: # 구글 사이트 확인 코드가 있으면 여기에 입력
naver_site_verification: # 네이버 사이트 확인 코드가 있으면 여기에 입력

# 사이트 구조화 데이터
structured_data:
  type: "LocalBusiness"
  business_type: "응급환자이송 서비스"
  price_range: "$$"
  opening_hours: "Mo-Su 00:00-24:00"
